edanalytics/lightbeam

- lightbeam/api.py
lightbeam uses the Ed-Fi API's dependencies endpoint to determine in which order to send resources. In Ed-Fi 5.1, this endpoint appears to have sorted resources in order. However E-d-Fi 6.1 produces the resources alphabetically. Moreover, it may show a resource twice (one with Create operation, another with Update operation), which caused lightbeam to send that resource twice.
This PR fixes this bug by filtering the list of resources returned by the dependencies endpoint to only those with a Create operation, and then sorting the resources according to the order property.
> fixing a bug with Ed-Fi 6.1 APIs dependencies

- README.md
- lightbeam/__main__.py
- lightbeam/lightbeam.py
- lightbeam/send.py
This PR implements the structured output portion of [this issue](https://github.com/edanalytics/lightbeam/issues/8). (A separate one will be coming to implement the exit code portion.) It adds the `--results-file` flag which allows you to specify an output to file to which earthmover will write a structured JSON run summary.
Example JSON output can be found in the addition to the README in this PR.
> adding structured output option

- lightbeam/send.py
If `lightbeam` skips sending all payloads because state tracking is enabled and no payloads have changed, we now exit with code 99 to signal Airflow (or other apps) to skip downstream tasks.
> adding skip exit code for lightbeam

- lightbeam/send.py
This PR fixes a bug where if the path to the specified results_file does not exist, lightbeam would fail instead of just creating it.
> create results_file path if it does not already exist

- lightbeam/api.py
This PR fixes a typo I discovered in the header of the CSV of descriptor values lightbeam creates. It's non-breaking, since [the code that uses it](https://github.com/edanalytics/lightbeam/blob/5f09fcf0b9e2d7f0ee41b5d2b6da828e2742d4c6/lightbeam/validate.py#L114) refers to columns by index, not name.
> fix typo in descriptor CSV header

- lightbeam/fetch.py
[lightbeam's `fetch` command](https://github.com/edanalytics/lightbeam#fetch) first `count`s the number of records in each resource before actually `fetch`ing them (in order to know how many pages of results to `fetch`). This relatively simple PR fixes a bug where lightbeam would die with an exception when trying to access the record counts for resources we don't have permission to read.
> fixes a bug when fetching resources without read permission

- lightbeam/send.py
This also
* sorts the failure line numbers (could be done in whatever consumes these logs, but why not do it here)
* fixes a bug where, when multiple files were sent for a resource, the line numbers for the next file didn't reset down to 0 between files
> updating structured logging to be flatter, per recent team discussion

- lightbeam/api.py
- lightbeam/validate.py
@megan-nash-ea pointed out that in Ed-Fi 7.1, `definitions` in Swagger were renamed to `components.schemas`. `definitions` were hard-coded, this PR makes lightbeam also look for `components.schemas` instead (if that exists), and also throws an error if nether `definitions` nor `components.schemas` exist.
> `definitions` in swagger were renamed to `components.schemas` in Ed-Fi 7.1

- lightbeam/validate.py
I found a bug when trying to validate an assessment record where the `assessment.performanceLevels[x].performanceLevelDescriptor` referred to a value that definitely existed locally (in a `performanceLevelDescriptors.jsonl` file) but `lightbeam validate` failed anyway. Turns out there was a bug in the recursive calls within `has_invalid_descriptor_values()` of `validate.py`; this PR fixes it.
> fixes a bug with validating local descriptor values within nested payloads

- lightbeam/api.py
The new implementation of wildcard support in `--keep-keys` and `--drop-keys` apparently makes `load_descriptors_values()` drop all the keys from descriptor value payloads, resulting in an key error. (Thanks to @megan-nash-ea for pointing out this issue.) This PR fixes the bug by first backing up any user-specified `keep-keys` and `drop-keys`, then explicitly setting `keep-keys=*` and `drop-keys=NULL` before fetching descriptor values from the Ed-Fi API.
> fixes a bug where none of the descriptor payload keys were kept after being downloaded

- CHANGELOG.md
- lightbeam/api.py
- lightbeam/delete.py
- lightbeam/send.py
- lightbeam/validate.py
Update the behavior of `lightbeam delete` so that hashlog entries are only removed after a confirmed successful delete. Fixes a bug where the `hash` variable was used in a scope for which it was not defined.
Also alter instances where `hash` is used as a variable name. I don't think it's a good idea to use Python builtins as variable names in general, and in this particular case I think it may have contributed to this bug not being found -- to a code editor, `hash` is always defined, so there was no problem to highlight in the delete.py file
> Fix how hashlog entries are handled during deletes

- README.md
- lightbeam/api.py
- lightbeam/lightbeam.py
The Lightbeam code assumes that there will be a json file at the root of the API url that defines where the auth, dependencies, and swagger metadata files are located.  However, this isn't always the case.  Indiana DOE's DEX system is an example, where the file does not exist in the expected location, and the metadata files are also not in their "default" urls relative to the base url.  
Previously, this would prevent Lightbeam from being used to connect to these non-standard APIs, since there was no way to manually define metadata urls for a connection.
This update adds 4 optional configuration options in the source/destination yaml files, to explicitly define the auth, dependencies, descriptor swagger, and resource swagger metadata files locations.  If these are defined in the yaml …
> Feature - Custom metadata URLs

- lightbeam/delete.py
- lightbeam/lightbeam.py
- lightbeam/truncate.py
Add visibility to delete/truncate operations by displaying the affected endpoints to the user. Implements Part 1 of the Dry Run feature described [here](https://edanalytics.slite.com/app/docs/cOqC2kYj_CHrRI) and tracked [here](https://educationanalytics.monday.com/boards/6058716254/pulses/6788662764)
> Feature: notify user of endpoints to be deleted

- lightbeam/api.py
The `description` field on Descriptors is optional in Ed-Fi, this fixes a bug in lightbeam (found by Luda) when they are missing.
> Fix missing descriptor description

- README.md
When [we changed](https://github.com/edanalytics/lightbeam/pull/24) the structure of the `--results-file` we never updated the example in the README. This PR fixes that.
> update readme for structured log to current format

- lightbeam/lightbeam.py
Split off from #45:
> This PR fixes a bug @megan-nash-ea pointed out where lightbeam send resulted in an error about lightbeam.get_endpoints_with_data() (which was recently refactored as part of the https://github.com/edanalytics/lightbeam/pull/30).
> Hotfix: bug with get_endpoints_with_data

- README.md
- lightbeam/lightbeam.py
- lightbeam/send.py
(Implementing the suggestion from @rlittle08 in [this issue](https://github.com/edanalytics/lightbeam/issues/39).)
> This adds a successes section to the structured log results file to report how many payloads resulted in a 200, 201, etc.

- README.md
- lightbeam/api.py
@rlittle08 was trying to manually specify a `dependencies_url` but found a bug, that [it doesn't work unless you also specify](https://github.com/edanalytics/lightbeam/blob/29301a6fd860b6f0d94d0848d3443b206a6e5445/lightbeam/api.py#L45) an `oauth_url`. This PR fixes that, allowing any of the following to be manually specified to override the defaults discovered from the `base_url`:
* `oauth_url`
* `dependencies_url`
* `open_api_metadata_url` or both `descriptors_swagger_url` and `resources_swagger_url`
A future improvement might be to also allow a custom `dataManagementApi` URL (instead of constructing it in `get_data_url()`), and to make the `mode`, `year`, and `version` optional, since those can also be discovered from the `base_url`.
Note that with these improvements, it is now …
> fixing bugs when some, but not all, custom API URLs are specified

- lightbeam/validate.py
`lightbeam` would previously crash if it encountered a descriptor value without a `#` (hash char) - an invalid format. This small PR fixes that behavior and provides a helpful validation error message to the user.
> fix `validate` of descriptor values without a hash char (`#`)

- lightbeam/api.py
- lightbeam/lightbeam.py
- lightbeam/util.py
- lightbeam/validate.py
`lightbeam validate` payload uniqueness previously (and _incorrectly_) checked uniqueness by _required_ properties; this PR makes it check uniqueness by properties with `x-Ed-Fi-isIdentity=true` in Swagger.
>  validate uniqueness by identity

- lightbeam/delete.py
- lightbeam/truncate.py
This PR removes the hard-coded prevention of `lightbeam delete` for `students`.
Note that if the Ed-Fi API uses a [relationship-based authorization strategy](https://edfi.atlassian.net/wiki/spaces/ODSAPIS3V500/pages/18350203/API+Claim+Sets+Resources#APIClaimSets&Resources-AuthorizationStrategies), you may run into the following situation:
You run `lightbeam delete`, which deletes records from resources in dependency-order. Since `studentEducationOrganizationAssociations` depend on `students`, the `stuEdOrgAssns` are (successfully) deleted first. However, now your EdOrg no longer has any relationship to your students, so when lightbeam subsequently attempts to delete `students`, the API returns 403 unauthorized status codes. There is no way to delete these students with your API …
> allow deletion of students (if permitted by credential claimset and API auth strategy)

- CHANGELOG.md
- lightbeam/lightbeam.py
Currently, this won't work:
```sh
lightbeam fetch --results-file results.json
```
You have to include a directory:
```sh
lightbeam fetch --results-file ./results.json
```
The former should be allowed
> Allow simple filename as `ressults-file`

- lightbeam/lightbeam.py
`lightbeam` looks for JSONL files in `data_dir` that correspond to an Ed-Fi endpoint (such as `students.jsonl`), and also subfolders in `data_dir` (such as `students/*.jsonl`). However, the data discovery code had a bug which would cause it to (silently!) skip/ignore such subfolders. This PR fixes the bug.
> fix discovery of data in subfolders of `data_dir`

- lightbeam/__main__.py
- lightbeam/lightbeam.py
This feature is analogous to the one [recently added](https://github.com/edanalytics/earthmover/pull/128) to earthmover. Examples:
```bash
lightbeam fetch --set fetch.page_size 1000
lightbeam validate --set log_level WARN show_stacktrace True
lightbeam send --set connection.timeout 15
```
> adds a `--set` flag to the CLI to enable overriding config values in `lightbeam.yml`

- lightbeam/util.py
- lightbeam/validate.py
This PR:
* fixes a bug which made the `uniqueness` validation method always succeed (as the uniqueness hash list was emptied before processing each payload)
* improves performance of the `uniqueness` validation method by moving certain preparatory steps (building the identity parameter structure, resolving the swagger reference definition, etc.) outside the payload processing loop (so it's only done once, not for every payload)
* implements recursive `uniqueness` validation of array elements within payloads, as requested/discussed in [this item](https://educationanalytics.monday.com/boards/6058716254/pulses/7475032702)
* improves validation error messages to include the validation _method_ that failed
> `validate` uniqueness fixes and recurse into array elements, other improvements

- README.md
Hi @tomreitz, the Ed-Fi Alliance has moved documentation from confluence to a new site hosted at docs.ed-fi.org. This PR provides updated links to the new documentation.
> Replace obsolete links to Ed-Fi Tech Docs

- lightbeam/validate.py
@johncmerfeld pointed out that `lightbeam validate` was throwing errors on the uniqueness check of subarrays even when elements of the arrays were, in fact, unique. This is because the structure used to track hashes of previously-seen elements was not emptied between records. This PR fixes that, emptying the tracking structure for every new record.
> fix subarray uniqueness bug

- lightbeam/lightbeam.py
This may not be the right way to approach this, maybe it's better to instead loop over the files/folders in the directory, lowercase them, and (for each) see if it matches the lowercased endpoint. (That would accommodate ridiculous things like `sTuDeNtScHoOlAsSoCiAtIoN.jsonl`.) Making this a draft PR, let's discuss.
> implement case flexibility for data discovery

- lightbeam/lightbeam.py
PR #31 introduced a bug where multiple casings of a file could be discovered, meaning a file would be processed several times. This is because, on some systems, `os.path.isfile()` is case-insensitive, so it would return `True` for both `Students.jsonl` and `students.jsonl`, and both "versions" of (the same) file would be processed. This PR ensures only one is added to the `file_list` and processed.
> fix duplicate file discovery
